# Generated by Django 3.2.7 on 2021-09-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
                ('chain_evolution', models.IntegerField()),
            ],
            options={
                'verbose_name': 'pokemon',
                'verbose_name_plural': 'pokemons',
            },
        ),
    ]
