# Generated by Django 3.2.7 on 2021-09-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ability',
                'verbose_name_plural': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='GameIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'game_indice',
                'verbose_name_plural': 'game_indices',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'move',
                'verbose_name_plural': 'moves',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('abilities', models.ManyToManyField(to='pokemon.Ability')),
            ],
            options={
                'verbose_name': 'pokemon',
                'verbose_name_plural': 'pokemons',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='PokemonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.stat')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonGameIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_index', models.IntegerField()),
                ('game_indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.gameindice')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_evolution', models.BooleanField(default=False)),
                ('evolution', models.ManyToManyField(related_name='_pokemon_pokemonevolution_evolution_+', to='pokemon.PokemonEvolution')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('pre_evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemonevolution')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution',
            field=models.ManyToManyField(related_name='_pokemon_pokemon_evolution_+', through='pokemon.PokemonEvolution', to='pokemon.Pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='forms',
            field=models.ManyToManyField(to='pokemon.Form'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='game_indices',
            field=models.ManyToManyField(through='pokemon.PokemonGameIndice', to='pokemon.GameIndice'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='pokemon.Move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stat',
            field=models.ManyToManyField(through='pokemon.PokemonStat', to='pokemon.Stat'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ManyToManyField(to='pokemon.Type'),
        ),
    ]
