# Generated by Django 3.2.7 on 2021-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20210917_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution',
            field=models.ManyToManyField(blank=True, null=True, related_name='_pokemon_pokemon_evolution_+', to='pokemon.Pokemon'),
        ),
    ]
